name: Deploy Hassiel Server 

on:
  push: 
    braches:
      -main

env:
  AWS_ACCESS_KEY_ID: ${{secret.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secret.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_DO_TOKEN: ${{secret.DO_TOKEN}}
  TF_VAR_MYSQL_DB: ${{secret.MYSQL_DB}}
  TF_VAR_MYSQL_HOST: ${{secret.MYSQL_HOST}}
  TF_VAR_MYSQL_PASSWORD: ${{secret.MYSQL_PASSWORD}}
  TF_VAR_MYSQL_USER: ${{secret.MYSQL_USER}}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Clon repository
        uses: actions/checkout@v4
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Create SSH Keys from secrets
        run:
          mkdir keys 
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ./keys/hassiel_server
          echo "${{secrets.SSH_PUBLIC_KEY}}" > ./keys/hassiel_server.pub
          chmod 777 ./keys/hassiel_server
          chmod 777 ./keys/hassiel_server.pub

      - name: Terraform fmt 
        run: terraform fmt
      
      - name: Terraform Validate 
        run: terraform validate 

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply


